### ISSUE TITLE
Destructure Structures

### ISSUE THREAD

**Issue by Havvy** [danielberkompas/destructure#2]
```
defmodule Foo do
  defstruct bar: 0

  import Destructure

  def take_foo(d%Foo{bar}) do
    :ok
  end
end
```

This fails to compile. I would like it to compile, and have `bar` in scope in `take_foo/1`.

**Comment by Havvy** [comment]
This needs to be re-opened (I don't have permission) for three reasons:

1. When trying to build a struct this way, the struct name doesn't get set.

```elixir
defmodule Foo do
  defstruct bar: 0

  import Destructure

  def new(bar), do: d%Foo{bar}
end

assert %Foo{bar: 1} == Foo.new(1)
```

Specifically, `Foo.new(1)` return `%{bar: 1}`.

2. Destructuring a different structure is possible.

```elixir
defmodule Baz
  defstruct bar: 0
end

assert d(%Foo{bar}) = %Baz{bar: 1}
```

This assert should fail. It doesn't. Meaning that a literal there doesn't provide (runtime) type safety.

3. Can't match on the struct name.

```elixir
d(%x{}) = %Foo{}
assert x == Foo
```

Currently this returns

```
** (FunctionClauseError) no function clause matching in Destructure.d/1
    (destructure) expanding macro: Destructure.d/1
```

**Comment by danielberkompas** [comment]
2 and 3 are valid points, so I'm reopening.

However, your first point is not. This code:

```elixir
def new(bar), do: d%{bar}
```

Compiles down to:

```elixir
def new(bar), do: %{bar: bar}
```

Nowhere in either version is the struct specified, so it isn't surprising that the `new/1` function returns a map, not a struct. Elixir doesn't treat the `new` function any different than any other function: to Elixir, it's just a function called `new`.

**Comment by Havvy** [comment]
Point 1 is valid. I just forgot to put the `Foo` in there. Edited to fix that.

For an iex example (using `A` because I had `Foo` defined already prior):

```
iex(18)> defmodule A do
...(18)> defstruct bar: 0
...(18)> 
...(18)> def new(bar), do: d%A{bar}
...(18)> end
{:module, A,
 <<70, 79, 82, 49, 0, 0, 9, 140, 66, 69, 65, 77, 69, 120, 68, 99, 0, 0, 0, 233,
   131, 104, 2, 100, 0, 14, 101, 108, 105, 120, 105, 114, 95, 100, 111, 99, 115,
   95, 118, 49, 108, 0, 0, 0, 4, 104, 2, ...>>, {:new, 1}}
iex(19)> A.new(2)
%{bar: 2}
```

**Comment by chouzan** [comment]
I see your point. I have to admit, my implementation is rather clumsy. I'll try to submit the patch soon.
