### ISSUE TITLE
Dynamic list of arguments in function definition

### ISSUE THREAD

**Issue by joaquimadraz** [danielberkompas/destructure#5]
Hey @danielberkompas, 

I was trying define a function that includes an argument that is being destructed like this:

```Elixir
  def some_fn(params = d%{name, email}, person \\ Person) do
    params
  end
```

And I got this error a compile error: `expected key-value pairs in a map, got: name`.

After a while digging into the code, I found out that if I define a new macro:

```Elixir
  defmacro d({:%{}, context, args}, person) do
```

..the compile error is gone. 

I'm still trying to get my head around meta programming in Elixir and this is confusing for me.
Why is `destructure` handling other arguments? 

Thanks 😃

**Comment by ssboisen** [comment]
Hi @joaquimadraz 

You should wrap your use of d in parentheses in this case

```
def some_fn(params = d(%{name, email}), person \\ Person) do
  params
end
```

**Comment by chouzan** [comment]
Hi @joaquimadraz, It's appear that the macro behave differently on matching operator. As @ssboisen suggest, you need to use parentheses in matching operator. Maybe someone more expert can explain why.

**Comment by joaquimadraz** [comment]
@ssboisen Cool, that solves the problem. Thanks!
